<?php
namespace wcf\util;

/**
 * Provides Font Awesome-related functions.
 * 
 * @author	Matthias Schmidt
 * @copyright	2014 Maasdt
 * @license	GNU Lesser General Public License <http://www.gnu.org/licenses/lgpl.html>
 * @package	com.maasdt.wcf.fontAwesomeIconUtil
 * @subpackage	util
 * @category	Community Framework
 */
final class FontAwesomeIconUtil {
	/**
	 * list with the icon names
	 * @var	array<string>
	 */
	protected static $icons = array(
		'adjust',
		'adn',
		'align-center',
		'align-justify',
		'align-left',
		'align-right',
		'ambulance',
		'anchor',
		'android',
		'angle-double-down',
		'angle-double-left',
		'angle-double-right',
		'angle-double-up',
		'angle-down',
		'angle-left',
		'angle-right',
		'angle-up',
		'apple',
		'archive',
		'arrow-circle-down',
		'arrow-circle-left',
		'arrow-circle-o-down',
		'arrow-circle-o-left',
		'arrow-circle-o-right',
		'arrow-circle-o-up',
		'arrow-circle-right',
		'arrow-circle-up',
		'arrow-down',
		'arrow-left',
		'arrow-right',
		'arrow-up',
		'arrows',
		'arrows-alt',
		'arrows-h',
		'arrows-v',
		'asterisk',
		'backward',
		'ban',
		'bar-chart-o',
		'barcode',
		'bars',
		'beer',
		'behance',
		'behance-square',
		'bell',
		'bell-o',
		'bitbucket',
		'bitbucket-square',
		'bold',
		'bolt',
		'bomb',
		'book',
		'bookmark',
		'bookmark-o',
		'briefcase',
		'btc',
		'bug',
		'building',
		'building-o',
		'bullhorn',
		'bullseye',
		'calendar',
		'calendar-o',
		'camera',
		'camera-retro',
		'car',
		'caret-down',
		'caret-left',
		'caret-right',
		'caret-square-o-down',
		'caret-square-o-left',
		'caret-square-o-right',
		'caret-square-o-up',
		'caret-up',
		'certificate',
		'chain-broken',
		'check',
		'check-circle',
		'check-circle-o',
		'check-square',
		'check-square-o',
		'chevron-circle-down',
		'chevron-circle-left',
		'chevron-circle-right',
		'chevron-circle-up',
		'chevron-down',
		'chevron-left',
		'chevron-right',
		'chevron-up',
		'child',
		'circle',
		'circle-o',
		'circle-o-notch',
		'circle-thin',
		'clipboard',
		'clock-o',
		'cloud',
		'cloud-download',
		'cloud-upload',
		'code',
		'code-fork',
		'codepen',
		'coffee',
		'cog',
		'cogs',
		'columns',
		'comment',
		'comment-o',
		'comments',
		'comments-o',
		'compass',
		'compress',
		'credit-card',
		'crop',
		'crosshairs',
		'css3',
		'cube',
		'cubes',
		'cutlery',
		'database',
		'delicious',
		'desktop',
		'deviantart',
		'digg',
		'dot-circle-o',
		'download',
		'dribbble',
		'dropbox',
		'drupal',
		'eject',
		'ellipsis-h',
		'ellipsis-v',
		'empire',
		'envelope',
		'envelope-o',
		'envelope-square',
		'eraser',
		'eur',
		'exchange',
		'exclamation',
		'exclamation-circle',
		'exclamation-triangle',
		'expand',
		'external-link',
		'external-link-square',
		'eye',
		'eye-slash',
		'facebook',
		'facebook-square',
		'fast-backward',
		'fast-forward',
		'fax',
		'female',
		'fighter-jet',
		'file',
		'file-archive-o',
		'file-audio-o',
		'file-code-o',
		'file-excel-o',
		'file-image-o',
		'file-o',
		'file-pdf-o',
		'file-powerpoint-o',
		'file-text',
		'file-text-o',
		'file-video-o',
		'file-word-o',
		'files-o',
		'film',
		'filter',
		'fire',
		'fire-extinguisher',
		'flag',
		'flag-checkered',
		'flag-o',
		'flask',
		'flickr',
		'floppy-o',
		'folder',
		'folder-o',
		'folder-open',
		'folder-open-o',
		'font',
		'forward',
		'foursquare',
		'frown-o',
		'gamepad',
		'gavel',
		'gbp',
		'gift',
		'git',
		'git-square',
		'github',
		'github-alt',
		'github-square',
		'gittip',
		'glass',
		'globe',
		'google',
		'google-plus',
		'google-plus-square',
		'graduation-cap',
		'h-square',
		'hacker-news',
		'hand-o-down',
		'hand-o-left',
		'hand-o-right',
		'hand-o-up',
		'hdd-o',
		'header',
		'headphones',
		'heart',
		'heart-o',
		'history',
		'home',
		'hospital-o',
		'html5',
		'inbox',
		'indent',
		'info',
		'info-circle',
		'inr',
		'instagram',
		'italic',
		'joomla',
		'jpy',
		'jsfiddle',
		'key',
		'keyboard-o',
		'krw',
		'language',
		'laptop',
		'leaf',
		'lemon-o',
		'level-down',
		'level-up',
		'life-ring',
		'lightbulb-o',
		'link',
		'linkedin',
		'linkedin-square',
		'linux',
		'list',
		'list-alt',
		'list-ol',
		'list-ul',
		'location-arrow',
		'lock',
		'long-arrow-down',
		'long-arrow-left',
		'long-arrow-right',
		'long-arrow-up',
		'magic',
		'magnet',
		'male',
		'map-marker',
		'maxcdn',
		'medkit',
		'meh-o',
		'microphone',
		'microphone-slash',
		'minus',
		'minus-circle',
		'minus-square',
		'minus-square-o',
		'mobile',
		'money',
		'moon-o',
		'music',
		'openid',
		'outdent',
		'pagelines',
		'paper-plane',
		'paper-plane-o',
		'paperclip',
		'paragraph',
		'pause',
		'paw',
		'pencil',
		'pencil-square',
		'pencil-square-o',
		'phone',
		'phone-square',
		'picture-o',
		'pied-piper',
		'pied-piper-alt',
		'pinterest',
		'pinterest-square',
		'plane',
		'play',
		'play-circle',
		'play-circle-o',
		'plus',
		'plus-circle',
		'plus-square',
		'plus-square-o',
		'power-off',
		'print',
		'puzzle-piece',
		'qq',
		'qrcode',
		'question',
		'question-circle',
		'quote-left',
		'quote-right',
		'random',
		'rebel',
		'recycle',
		'reddit',
		'reddit-square',
		'refresh',
		'renren',
		'repeat',
		'reply',
		'reply-all',
		'retweet',
		'road',
		'rocket',
		'rss',
		'rss-square',
		'rub',
		'scissors',
		'search',
		'search-minus',
		'search-plus',
		'share',
		'share-alt',
		'share-alt-square',
		'share-square',
		'share-square-o',
		'shield',
		'shopping-cart',
		'sign-in',
		'sign-out',
		'signal',
		'sitemap',
		'skype',
		'slack',
		'sliders',
		'smile-o',
		'sort',
		'sort-alpha-asc',
		'sort-alpha-desc',
		'sort-amount-asc',
		'sort-amount-desc',
		'sort-asc',
		'sort-desc',
		'sort-numeric-asc',
		'sort-numeric-desc',
		'soundcloud',
		'space-shuttle',
		'spinner',
		'spoon',
		'spotify',
		'square',
		'square-o',
		'stack-exchange',
		'stack-overflow',
		'star',
		'star-half',
		'star-half-o',
		'star-o',
		'steam',
		'steam-square',
		'step-backward',
		'step-forward',
		'stethoscope',
		'stop',
		'strikethrough',
		'stumbleupon',
		'stumbleupon-circle',
		'subscript',
		'suitcase',
		'sun-o',
		'superscript',
		'table',
		'tablet',
		'tachometer',
		'tag',
		'tags',
		'tasks',
		'taxi',
		'tencent-weibo',
		'terminal',
		'text-height',
		'text-width',
		'th',
		'th-large',
		'th-list',
		'thumb-tack',
		'thumbs-down',
		'thumbs-o-down',
		'thumbs-o-up',
		'thumbs-up',
		'ticket',
		'times',
		'times-circle',
		'times-circle-o',
		'tint',
		'trash-o',
		'tree',
		'trello',
		'trophy',
		'truck',
		'try',
		'tumblr',
		'tumblr-square',
		'twitter',
		'twitter-square',
		'umbrella',
		'underline',
		'undo',
		'university',
		'unlock',
		'unlock-alt',
		'upload',
		'usd',
		'user',
		'user-md',
		'users',
		'video-camera',
		'vimeo-square',
		'vine',
		'vk',
		'volume-down',
		'volume-off',
		'volume-up',
		'weibo',
		'weixin',
		'wheelchair',
		'windows',
		'wordpress',
		'wrench',
		'xing',
		'xing-square',
		'yahoo',
		'youtube',
		'youtube-play',
		'youtube-square'
	);
	
	/**
	 * maps old (v3) icon names to new (v4) icon names
	 * @deprecated	will be removed or updated with the next version, only rely
	 * on it when updating to this version
	 * @var	array<string>
	 */
	protected static $iconUpdates = array(
		'ban-circle' => 'ban',
		'bar-chart' => 'bar-chart-o',
		'beaker' => 'flask',
		'bell' => 'bell-o',
		'bell-alt' => 'bell',
		'bitbucket-sign' => 'bitbucket-square',
		'bookmark-empty' => 'bookmark-o',
		'building' => 'building-o',
		'calendar-empty' => 'calendar-o',
		'check-empty' => 'square-o',
		'check-minus' => 'minus-square-o',
		'check-sign' => 'check-square',
		'check' => 'check-square-o',
		'chevron-sign-down' => 'chevron-down',
		'chevron-sign-left' => 'chevron-left',
		'chevron-sign-right' => 'chevron-right',
		'chevron-sign-up' => 'chevron-up',
		'circle-arrow-down' => 'arrow-circle-down',
		'circle-arrow-left' => 'arrow-circle-left',
		'circle-arrow-right' => 'arrow-circle-right',
		'circle-arrow-up' => 'arrow-circle-up',
		'circle-blank' => 'circle-o',
		'cny' => 'rub',
		'collapse-alt' => 'minus-square-o',
		'collapse-top' => 'caret-square-o-up',
		'collapse' => 'caret-square-o-down',
		'comment-alt' => 'comment-o',
		'comments-alt' => 'comments-o',
		'copy' => 'files-o',
		'cut' => 'scissors',
		'dashboard' => 'tachometer',
		'double-angle-down' => 'angle-double-down',
		'double-angle-left' => 'angle-double-left',
		'double-angle-right' => 'angle-double-right',
		'double-angle-up' => 'angle-double-up',
		'download' => 'arrow-circle-o-down',
		'download-alt' => 'download',
		'edit' => 'pencil-square-o',
		'edit-sign' => 'pencil-square',
		'ellipsis-horizontal' => 'ellipsis-h',
		'ellipsis-vertical' => 'ellipsis-v',
		'envelope-alt' => 'envelope-o',
		'exclamation-sign' => 'exclamation-circle',
		'expand-alt' => 'plus-square-o',
		'expand' => 'caret-square-o-right',
		'external-link-sign' => 'external-link-square',
		'eye-close' => 'eye-slash',
		'eye-open' => 'eye',
		'facebook-sign' => 'facebook-square',
		'facetime-video' => 'video-camera',
		'file-alt' => 'file-o',
		'file-text-alt' => 'file-text-o',
		'flag-alt' => 'flag-o',
		'folder-close-alt' => 'folder-o',
		'folder-close' => 'folder',
		'folder-open-alt' => 'folder-open-o',
		'food' => 'cutlery',
		'frown' => 'frown-o',
		'fullscreen' => 'arrows-alt',
		'github-sign' => 'github-square',
		'google-plus-sign' => 'google-plus-square',
		'group' => 'users',
		'h-sign' => 'h-square',
		'hand-down' => 'hand-o-down',
		'hand-left' => 'hand-o-left',
		'hand-right' => 'hand-o-right',
		'hand-up' => 'hand-o-up',
		'hdd' => 'hdd-o',
		'heart-empty' => 'heart-o',
		'hospital' => 'hospital-o',
		'indent-left' => 'outdent',
		'indent-right' => 'indent',
		'info-sign' => 'info-circle',
		'keyboard' => 'keyboard-o',
		'legal' => 'gavel',
		'lemon' => 'lemon-o',
		'lightbulb' => 'lightbulb-o',
		'linkedin-sign' => 'linkedin-square',
		'mail-reply-all' => 'reply-all', // mail-reply-all is an alias which was included previously by accident
		'meh' => 'meh-o',
		'microphone-off' => 'microphone-slash',
		'minus-sign-alt' => 'minus-square',
		'minus-sign' => 'minus-circle',
		'mobile-phone' => 'mobile',
		'moon' => 'moon-o',
		'move' => 'arrows',
		'off' => 'power-off',
		'ok-circle' => 'check-circle-o',
		'ok-sign' => 'check-circle',
		'ok' => 'check',
		'paper-clip' => 'paperclip',
		'paste' => 'clipboard',
		'phone-sign' => 'phone-square',
		'picture' => 'picture-o',
		'pinterest-sign' => 'pinterest-square',
		'play-circle' => 'play-circle-o',
		'play-sign' => 'play-circle',
		'plus-sign-alt' => 'plus-square',
		'plus-sign' => 'plus-circle',
		'pushpin' => 'thumb-tack',
		'question-sign' => 'question-circle',
		'remove-circle' => 'times-circle-o',
		'remove-sign' => 'times-circle',
		'remove' => 'times',
		'reorder' => 'bars',
		'resize-full' => 'expand',
		'resize-horizontal' => 'arrows-h',
		'resize-small' => 'compress',
		'resize-vertical' => 'arrows-v',
		'rss-sign' => 'rss-square',
		'save' => 'floppy-o',
		'screenshot' => 'crosshairs',
		'share-alt' => 'share',
		'share-sign' => 'share-square',
		'share' => 'share-square-o',
		'sign-blank' => 'square',
		'signin' => 'sign-in',
		'signout' => 'sign-out',
		'smile' => 'smile-o',
		'sort-by-alphabet-alt' => 'sort-alpha-desc',
		'sort-by-alphabet' => 'sort-alpha-asc',
		'sort-by-attributes-alt' => 'sort-amount-desc',
		'sort-by-attributes' => 'sort-amount-asc',
		'sort-by-order-alt' => 'sort-numeric-desc',
		'sort-by-order' => 'sort-numeric-asc',
		'sort-down' => 'sort-desc',
		'sort-up' => 'sort-asc',
		'stackexchange' => 'stack-overflow',
		'star-empty' => 'star-o',
		'star-half-empty' => 'star-half-o',
		'sun' => 'sun-o',
		'thumbs-down-alt' => 'thumbs-o-down',
		'thumbs-up-alt' => 'thumbs-o-up',
		'time' => 'clock-o',
		'trash' => 'trash-o',
		'tumblr-sign' => 'tumblr-square',
		'twitter-sign' => 'twitter-square',
		'unlink' => 'chain-broken',
		'upload' => 'arrow-circle-o-up',
		'upload-alt' => 'upload',
		'warning-sign' => 'exclamation-triangle',
		'xing-sign' => 'xing-square',
		'youtube-sign' => 'youtube-square',
		'zoom-in' => 'search-plus',
		'zoom-out' => 'search-minus'
	);
	
	/**
	 * defines the version of Font Awesome the util belongs to
	 * @var	string
	 */
	const FONT_AWESOME_VERSION = '4.1.0';
	
	/**
	 * Returns the CSS class name of the given icon.
	 * 
	 * @param	string		$icon
	 * @return	string
	 */
	public static function getCSSClassName($icon) {
		return 'fa-'.$icon;
	}
	
	/**
	 * Returns the available icons.
	 * 
	 * @return	array<string>
	 */
	public static function getIcons() {
		return self::$icons;
	}
	
	/**
	 * Returns an update map to convert old icon names into new icon names.
	 * 
	 * @return	array<string>
	 */
	public static function getIconUpdates() {
		return self::$iconUpdates;
	}
	
	
	/**
	 * Returns the LESS variable name of the given icon.
	 * 
	 * @param	string		$icon
	 * @return	string
	 */
	public static function getLESSVariableName($icon) {
		return 'fa-var-'.$icon;
	}
	
	/**
	 * Returns true if the given icon exists.
	 * 
	 * @param	string		$icon
	 * @return	boolean
	 */
	public static function isValid($icon) {
		return in_array($icon, self::$icons);
	}
	
	/**
	 * Disables creating FontAwesomeIconUtil objects.
	 */
	private function __construct() {
		// does nothing
	}
}
